server:
    port: 8001
spring:
    application:
        name: AdminUser-UI

#thymeleaf默认为HTML5 验证不友好 体验不佳
    thymeleaf:
        content-type: text/html 
        cache: false 
        mode: LEGACYHTML5

#Json返回日期格式
    jackson:
        date-format: yyyy-MM-dd HH\:mm\:ss
        time-zone: GMT+8

#eureka.client.register-with-eureka=false

#Eureka地址
eureka:
    client:
        service-url:
            defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka
    instance:
        instance-id: AdminUserUI-8001
        prefer-ip-address: true

info:
    app:
        name: AdminUser-UI
    company:
        name: hand
    build:
        artifactId: $project.artifactId$
        version: $project.version$
